name: Deploy static content to Pages

on:
  push:
    branches: ["main"]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write
  issues: write
  repository-projects: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: check server
        run: set +e ; httpd -t ; nginx -v ; set -e ;

      - uses: actions/checkout@v3

      # use Node cache
      - uses: actions/setup-node@v3
        with:
          node-version: 16.14

      - run: npm ci && npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages  # default: gh-pages
